@FileworxNews.WebApi_HostAddress = http://localhost:5265

GET {{FileworxNews.WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###
POST https://localhost:7186/api/User
Content-Type: application/json

### POST Request to Create User
### POST Request to Create User
### POST Request to Create or Update User
POST https://localhost:7186/api/User
Content-Type: application/json

{
  "Id": "64EA4A06-05D1-41E1-B842-604A49A45654",
  "Name": "Sample Fileworx Entity new new new",
  "CreationDate": "2025-03-09T12:34:56Z",
  "LastModificationDate": "2025-03-09T12:34:56Z",
  "LastModifierId": "01175F83-7D23-4D21-B090-32D2E1257F4E",
  "CreatorId": "01175F83-7D23-4D21-B090-32D2E1257F4E",
  "Password": "123" ,
  "LogInName":"Mohammad"
}
###
POST https://localhost:7186/FileworxNews/Controller
Content-Type: application/json

{
  "Name": "Sample cc",
  "Description": "This is a sample content description.",
  "Body": "This is the body of the content."
 
}
### 
GET https://localhost:7186/FileworxNews/Controller/CEF100EA-3546-4AE3-9825-1BC7D75457D0

###
GET https://localhost:7186/FileworxNews/Controller
### 
DELETE https://localhost:7186/FileworxNews/Controller/a166237a-a541-494c-8fd1-c70cf5fa22cb
###

PUT https://localhost:7186/FileworxNews/Controller/cef100ea-3546-4ae3-9825-1bc7d75457d0
Content-Type: application/json

{
  "Name": "uPDATED BY PUT",
  "Description": "UPDATED BY pUT.",
  "Body": "This is the body of the content."
 
}